import '../globals.css';
import Link from 'next/link';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeChangeProvider from '@/theme-store/theme-store';
import { CssBaseline } from '@mui/material';
import { Analytics } from '@vercel/analytics/react';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider>
          <ThemeChangeProvider>
            <CssBaseline />
            {children}
            <Analytics />
          </ThemeChangeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
